# название
name: Project test & build

# целевые события для запуска
# в данном случае это push и pull_request, в ветку master
on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

permissions:
    contents: write

# выполняемые действия
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        # запускаются по шагам
        # name - название шага
        # в github actions будет выводиться название шага, и процессы
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1

            - name: Install 🔧
              run: npm install

            - name: Build 👷
              run: npm run build
              env:
                  REACT_APP_FIREBASE_KEY: ${{ secrets.REACT_APP_FIREBASE_KEY }}

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4.3.3
              with:
                  branch: gh-pages # The branch the action should deploy to.
                  folder: build # The folder the action should deploy.
